-- =====================================================
-- GardenGuard Monitor - Supabase Database Schema
-- =====================================================
-- Run this SQL in your Supabase project's SQL Editor
-- to set up the database for the GardenGuard app.
-- =====================================================

-- Create the updates table
CREATE TABLE IF NOT EXISTS public.updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garden TEXT NOT NULL,
  type TEXT NOT NULL,
  plant_id TEXT NOT NULL,
  desc TEXT NOT NULL,
  media TEXT,
  media_type TEXT DEFAULT 'image/jpeg',
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index on garden for faster queries
CREATE INDEX IF NOT EXISTS updates_garden_idx ON public.updates(garden);

-- Create index on created_at for sorting
CREATE INDEX IF NOT EXISTS updates_created_at_idx ON public.updates(created_at DESC);

-- Create a storage bucket for media files
-- Note: This requires the storage extension to be enabled
INSERT INTO storage.buckets (id, name, public)
VALUES ('media', 'media', true)
ON CONFLICT (id) DO NOTHING;

-- Set up Row Level Security (RLS) policies
ALTER TABLE public.updates ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read updates (for public access)
CREATE POLICY "Allow public read access"
  ON public.updates FOR SELECT
  TO public
  USING (true);

-- Allow anyone to insert updates (you may want to restrict this later)
CREATE POLICY "Allow public insert access"
  ON public.updates FOR INSERT
  TO public
  WITH CHECK (true);

-- Allow anyone to update updates
CREATE POLICY "Allow public update access"
  ON public.updates FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

-- Allow anyone to delete updates
CREATE POLICY "Allow public delete access"
  ON public.updates FOR DELETE
  TO public
  USING (true);

-- Set up storage policies for media bucket
CREATE POLICY "Allow public upload to media"
  ON storage.objects FOR INSERT
  TO public
  WITH CHECK (bucket_id = 'media');

CREATE POLICY "Allow public read from media"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'media');

CREATE POLICY "Allow public delete from media"
  ON storage.objects FOR DELETE
  TO public
  USING (bucket_id = 'media');

-- =====================================================
-- NOTES:
-- =====================================================
-- 1. Make sure the Storage extension is enabled in Supabase
-- 2. You can restrict access by adding authentication later
-- 3. The policies above allow public access - add auth checks for production
-- 4. Update your .env.local file with your Supabase credentials
-- =====================================================

-- =====================================================
-- PLANT MANAGEMENT TABLES
-- =====================================================

-- Gardens table
CREATE TABLE IF NOT EXISTS public.gardens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Plant types table
CREATE TABLE IF NOT EXISTS public.plant_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Plants table
CREATE TABLE IF NOT EXISTS public.plants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garden_id BIGINT NOT NULL REFERENCES public.gardens(id) ON DELETE CASCADE,
  plant_type_id BIGINT NOT NULL REFERENCES public.plant_types(id) ON DELETE CASCADE,
  plant_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS plants_garden_id_idx ON public.plants(garden_id);
CREATE INDEX IF NOT EXISTS plants_plant_type_id_idx ON public.plants(plant_type_id);

-- Enable Row Level Security
ALTER TABLE public.gardens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plant_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plants ENABLE ROW LEVEL SECURITY;

-- Gardens policies
CREATE POLICY "Allow public read access on gardens"
  ON public.gardens FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert access on gardens"
  ON public.gardens FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update access on gardens"
  ON public.gardens FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

-- Plant types policies
CREATE POLICY "Allow public read access on plant_types"
  ON public.plant_types FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert access on plant_types"
  ON public.plant_types FOR INSERT
  TO public
  WITH CHECK (true);

-- Plants policies
CREATE POLICY "Allow public read access on plants"
  ON public.plants FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert access on plants"
  ON public.plants FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update access on plants"
  ON public.plants FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public delete access on plants"
  ON public.plants FOR DELETE
  TO public
  USING (true);

-- Insert default gardens
INSERT INTO public.gardens (name) VALUES
  ('Kebun Rumah Klegen'),
  ('Kebun Balai Desa')
ON CONFLICT (name) DO NOTHING;

-- Insert default plant types
INSERT INTO public.plant_types (name) VALUES
  ('Mangga'),
  ('Matoa'),
  ('Alpukat')
ON CONFLICT (name) DO NOTHING;
