-- =====================================================
-- Migration: Add Conditions Table for Plant Monitoring
-- Run this SQL in your Supabase project's SQL Editor
-- =====================================================

-- Create conditions table
CREATE TABLE IF NOT EXISTS public.conditions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#10B981',
  icon TEXT NOT NULL DEFAULT '✅',
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS conditions_display_order_idx ON public.conditions(display_order);
CREATE INDEX IF NOT EXISTS conditions_is_active_idx ON public.conditions(is_active);

-- Enable Row Level Security
ALTER TABLE public.conditions ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access on conditions"
  ON public.conditions FOR SELECT
  TO public
  USING (true);

-- Allow public insert access
CREATE POLICY "Allow public insert access on conditions"
  ON public.conditions FOR INSERT
  TO public
  WITH CHECK (true);

-- Allow public update access
CREATE POLICY "Allow public update access on conditions"
  ON public.conditions FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

-- Allow public delete access
CREATE POLICY "Allow public delete access on conditions"
  ON public.conditions FOR DELETE
  TO public
  USING (true);

-- Add condition_id column to updates table
ALTER TABLE public.updates ADD COLUMN IF NOT EXISTS condition_id BIGINT REFERENCES public.conditions(id) ON DELETE SET NULL;

-- Create index on condition_id for filtering
CREATE INDEX IF NOT EXISTS updates_condition_id_idx ON public.updates(condition_id);

-- Insert default conditions
INSERT INTO public.conditions (name, slug, color, icon, display_order) VALUES
  ('🟢 Healthy', 'healthy', '#10B981', '✅', 1),
  ('🌸 Flowering', 'flowering', '#EC4899', '🌸', 2),
  ('🍊 Bearing Fruit', 'bearing-fruit', '#F97316', '🍊', 3),
  ('💊 Needs Treatment', 'needs-treatment', '#F59E0B', '💊', 4),
  ('❌ Dead', 'dead', '#EF4444', '❌', 5),
  ('📝 General Note', 'general', '#6B7280', '📝', 6)
ON CONFLICT (slug) DO NOTHING;

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update updated_at
CREATE TRIGGER update_conditions_updated_at
  BEFORE UPDATE ON public.conditions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
